---
name: check_git_status
windows:
  - tabs:
      - title: tab1
        color: red
        layout:
          cwd: /Users/arfan2
          commands:
            - exec: cd "$HOME/Developer/gh"
            - exec: uv run --with rich $HOME/Developer/gh/web-apps/SCRIPTS/py/git-status-script/git_status_table.py
